fix: 테이블 스크롤 css, 체크박스 기능 및 기타 스타일 수정
ez-mail/ez-mail-client-web pull request #19
Opened 2023-02-20 02:08 UTC by pinomad

1. subscribers, emaileditingstep01 화면 테이블 스크롤 다른화면과 동일하게 수정
2. subscribers, emaileditingstep01 화면 테이블 체크박스 state 관리되게 수정
3. emails, subscribers 버튼과 컨텐츠 간격 조정
4. subscribersAdditon 화면 Nav-구독자 글자 검정색으로 나오게 수정
5. emaileditingstep02 화면 input들 state로 관리되게 수정

2023-02-20 02:19 UTC, roadzmoon76 requested changes
띄워쓰기 컨벤션은 저희 문서를 참고하여 최대한 지켜주셨으면 합니다.

아래쪽은 계속 같은 방식의 띄워쓰기 실수를 하셔서 코멘트는 생략했습니다.

또 어제 얘기 나눴던거랑 다른 방향으로 구현이 된 것 같은데 어떤 플로우를 생각하고 계신건지 설명 부탁드립니다.

2023-02-20 02:19 UTC, roadzmoon76 commented on src/components/DashboardNav.jsx
> +              location.pathname.includes('/subscribers') ? 'black' : null
왜 이렇게 바꾸신걸까요?

2023-02-20 02:19 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +    setIsCheckedAll(!isCheckedAll);
변수 선언부랑 띄워쓰기 부탁드립니다

2023-02-20 02:19 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +      return item;
리턴문 띄워쓰기 부탁드립니다

2023-02-20 02:19 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +    setCheckedItems(newItems);
변수 선언부 띄워쓰기 부탁드립니다.

2023-02-20 02:19 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +    console.log(checkedRow); // 삭제될 row
변수 선언부 띄워쓰기 or 콘솔은 위아래 띄워쓰기 적용 부탁드립니다

2023-02-20 02:19 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
왜 data 그 자체를 스테이트로 넣게 된걸까요?

목데이터에는 왜 `checked: false` 항목이 생겼나요?

정진님이 생각하시는 플로우가 어떤건지 자세하게 설명 부탁드립니다.

2023-02-20 02:23 UTC, pinomad commented on src/components/DashboardNav.jsx
> +              location.pathname.includes('/subscribers') ? 'black' : null
구독자 화면에서 추가화면 /subscribers/addition 으로 넘어가면 선택되어있는 NAV-구독자 글자가 다시 회색으로 바껴서 수정했습니다.

2023-02-20 02:39 UTC, pinomad commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
https://github.com/ez-mail/ez-mail-client-web/blob/42c96c89b461f1e608c6fa757b274d08a8f44633/src/pages/emails/EmailEditingStep01.jsx#L131
checkbox를 누를때마다 즉, state가 바뀔때마다 이곳에서 check가 반영된 checkedItems로 컴포넌트를 뿌려주는 형태로 작성했습니다. row하나씩 input의 checked프로퍼티를 관리하기위해 data에 checked property를 넣었습니다.

2023-02-20 02:42 UTC, pinomad commented on src/pages/emails/EmailEditingStep01.jsx
> +    console.log(checkedRow); // 삭제될 row
변수 선언은 붙이고 콘솔은 아래만 띄우는건줄 알았는데 다 띄우는거였네요 개행 부분 전부 반영하였습니다.

2023-02-20 02:52 UTC, pinomad commented
>

2023-02-20 02:55 UTC, roadzmoon76 requested changes
코멘트 의견 부탁드립니다

2023-02-20 02:55 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
그럼 구독자 리스트를 받아오면 isCheckd 항목을 추가해주는 로직과 다시 patch 하기 전에 isChecked 항목을 삭제해주는 함수도 필요하지 않을까요?

우리가 서버에서 보내주는 데이터는 저런 형태가 아닌데 저런 형태로 가공을 해주는 유틸함수가 안보여서요.

2023-02-20 03:38 UTC, pinomad commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
1. 그럼 구독자 리스트를 받아오면 isCheckd 항목을 추가해주는 로직과 다시 patch 하기 전에 isChecked 항목을 삭제해주는 함수도 필요하지 않을까요?
-> 구독자 리스트를 받아오면 checked 프로퍼티를 추가해주는 로직은 필요하겠네요 patch 하기 전에 isChecked 항목을 삭제해주는 함수는 필요없을것같아요 백엔드에서는 필요한 정보만 갖다 쓰면 되니까요. 아마 id만 있으면 되지않을까 싶어요

2. 그리고 state 에 처음부터 subscribersData 로 초기화가 되는건 좀 이상한 것 같아요. 처음엔 빈배열로 초기화가 되고 서버에서 데이터를 받아오면 state 가 설정되어야 하지 않을까요?
-> 이부분은 잘 이해가 안갑니다. 서버에서 받아온 데이터로 state초기화를 하면 안되는건가요? 제가 놓치는게 있다면 말씀해주세요

state 변수명도 담기는 내용을 유추하기가 힘든 것 같습니다.
-> 이거는 한번 수정해보겠습니다.

마지막으로 굳이 받아오는 데이터 전체를 state 에 넣어야 하는가도 의문이 듭니다. 결국 실질적으로 UI 상태가 바뀌는건 체크박스 뿐인데 리액트의 설계 의도와는 조금 다른 state 관리가 아닌가 생각듭니다.
-> 리액트의 설계의도가 뭔지 잘 몰라서 답변하기가 어렵네요 데이터 전체를 state에 넣으면 안되는 이유가 있을까요? 서버에서 필요한 데이터는 결국 id라서 id만 있으면 되는건 맞는데 데이터양이 많지가 않아서 굳이 데이터 가공을 하지 않았거든요

2023-02-20 03:41 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
요 부분은 오늘 일정을 어느정도 마무리 하고 밤에 회의 해보는 걸로 합시다!

2023-02-20 12:25 UTC, roadzmoon76 requested changes
변수명 부분 코멘트 다시 달았습니다~ 확인해주세요!

2023-02-20 12:25 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
변수명은 결국 구독자들을 담는 거니 subscribers 나 isCheckdAddedSubscribers 정도가 좋을 것 같습니다.

2023-02-20 12:28 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +  const [checkedItems, setCheckedItems] = useState(subscribersData);
아 그리고 api 플로우를 생각해보면 해당 state 는 빈배열로 초기화되는게 맞는 것 같습니다.

2023-02-20 12:38 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep01.jsx
> +    checked: false,
속성 명은 불리언이니 `isChecked` 로 하시는게 좋을 것 같습니다.

2023-02-21 02:06 UTC, roadzmoon76 approved these changes
수고하셨습니다~

2023-02-21 02:27 UTC, merged