feat: 드래그 드랍 적용
ez-mail/ez-mail-client-web pull request #34
Opened 2023-03-02 05:03 UTC by pinomad

드래그& 드랍 적용했습니다.

### 참고사항
자잘한 버그들이 있습니다. 차차 수정해보겠습니다.
1. 버튼 컴포넌트 클릭시 포커스가 간헐적으로 작동안함
2. 내가 원하는 곳에 boxshadow가 제대로 안생기는 경우가 있음 -> 아래로 옮길때만 발생함
3. 드래그 후 컨텐츠박스자체가 draggable 상태가 됨. 

사용해보시면서 버그 발견하면 제보해주세요

2023-03-02 12:42 UTC, roadzmoon76 requested changes
코멘트 부분 수정해서 푸쉬 부탁드립니다.

2023-03-02 12:42 UTC, roadzmoon76 commented on package.json
> +  "version": "0.24.1",
버전은 브랜치 단위로 올려야 하고 처음 기능 추가니 0.24.0 이 맞는 것 같아요.

2023-03-02 12:42 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
> +      isActive: false,
이게 실제 백엔드에 들어가면 안되는 정보라 관련 정보를 추가하고 제거해주는 유틸함수가 필요해보입니다.

2023-03-02 12:42 UTC, roadzmoon76 commented on src/components/emailEditingStep03/BoxTool.jsx
> +    switch (type) {
한칸 띄워주세요

2023-03-02 12:42 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
> +  const dragItem = useRef();
html 요소 ref 는 `$dragItemRef` 이런식으로 통일하면 좋을 것 같아요

2023-03-02 12:42 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
> +      return item;
띄워쓰기

2023-03-02 13:22 UTC, pinomad commented on package.json
> +  "version": "0.24.1",
아 그러네요 저도 똑같은실수를...

2023-03-02 13:22 UTC, pinomad commented on src/pages/emails/EmailEditingStep03.jsx
> +      isActive: false,
유틸함수 추가하였습니다.

2023-03-02 13:22 UTC, pinomad commented on src/pages/emails/EmailEditingStep03.jsx
> +  const dragItem = useRef();
넵 반영하였습니다.

2023-03-02 13:26 UTC, roadzmoon76 requested changes

2023-03-02 13:26 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
> +  const $dragItem = useRef();
$dragItemRef 라고 하기로 했잖아요...🥲
`$dragItem === $dragItemRef.current`

2023-03-02 13:54 UTC, pinomad commented on src/pages/emails/EmailEditingStep03.jsx
> +  const $dragItem = useRef();
😰 수정하였습니다

2023-03-02 13:58 UTC, roadzmoon76 approved these changes
고생하셨어요

머리 쓰는거 많이 해서 과열됐으니 잠깐 단순한거 하면서 식히고 버그는 다시 고쳐봐요

2023-03-02 13:58 UTC, merged

2023-03-05 12:42 UTC, roadzmoon76 commented on src/components/emailEditingStep03/BoxTool.jsx
> +          isActive: false,
ui 로직을 위한 정보는 wrraper 컴포넌트에 있었으면 더 좋았을 것 같습니다.

해당 부분은 나중에 리팩토링 할 때 반영하죠.

2023-03-05 12:44 UTC, roadzmoon76 commented on src/components/emailEditingStep03/contentWrapper.jsx
> +    <Wrapper
저는 드래그앤드랍 로직들이 이 컨텐츠 wrapper 컴포넌트에 놔달라고 말씀드린거였는데 의사소통이 제대로 안된 것 같아 많이 아쉽네요.

나중에 리팩토링 때 고쳐보면 좋을 것 같습니다.

2023-03-05 12:45 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
> +  const handleDraggable = e => {
이 컴포넌트는 딱 데이터를 받아서 뿌려주는 로직만 있게하도록 처음 구조를 짠거였는데 제대로 전달이 안된 것 같아 아쉽습니다.

데이터들과 드래그앤 드랍을 위한 로직들이 섞여서 컴포넌트가 너무 무거워진 것 같아요.

나중에 리팩토링 합시다.

2023-03-05 12:47 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
> +    setEmailContentsData(addProperties(emailTemplateData.emailContents));
제가 목데이터를 위와 같이 짰던 이유는 나중에 아톰에도 그대로 들어가는 거라 그 자체로 다뤄주기를 바랬던건데 이렇게 하면 나중에 리액트 쿼리나 리코일을 적용할 때 나눠서 넣야해서 많이 복잡해 질 것 같습니다...

그냥 위의 데이터 자체를 업데이트 해주는 로직을 immer 를 사용해 구현하는게 좋을 것 같습니다.