Feature/step3 recoil query
ez-mail/ez-mail-client-web pull request #44
Opened 2023-03-04 13:26 UTC by pinomad

2023-03-04 13:38 UTC, roadzmoon76 requested changes

2023-03-04 13:38 UTC, roadzmoon76 commented on src/recoil/emailTemplate/atom.js
> +  key: 'emailTemplate',
key 값을 emailTemplateData 로 주는게 더 좋을 것 같아요

2023-03-04 13:50 UTC, pinomad commented on src/recoil/emailTemplate/atom.js
> +  key: 'emailTemplate',
반영하였습니다.

2023-03-04 22:44 UTC, roadzmoon76 requested changes
`components/emailEditingStep03` 에 있는 TextContent 컴포넌트와 ButtonContent 컴포넌트의 contentHTML 에도 리코일 적용해야 합니다.

자세한 설명은 허들로 말씀드릴게요.

또 말씀하신 input range 는 값이 px가 포함된 문자열로 들어가서 그런 것 같습니다. 해당 문자열을 숫자로 바꿔주는 유틸함수를 만드셔서 적용하시면 정상 작동 할거에요.

2023-03-05 02:27 UTC, roadzmoon76 approved these changes
복잡한 작업이였는데 정말 고생하셨습니다🥹

2023-03-05 05:10 UTC, merged

2023-03-05 05:36 UTC, roadzmoon76 commented on src/components/emailEditingStep03/StyleControlPanels/SpacerContainer.jsx
>            onChange={e => handleBoxStyleChange(e)}
핸들러가 중첩되서 적혀있네요

`onChange={handleBoxStyleChange}` 이런식으로 전부 수정해주세요