fix: 주요 기능 관련 에러 수정
ez-mail/ez-mail-client-web pull request #57
Opened 2023-03-11 17:25 UTC by pinomad

1. step2에서 step3넘어갈때 안넘어가는 버그 -> 재현이 불가하여 원인이 될만한곳에 방어로직을 추가했습니다.
2. step2에서 제목 수정 후 뒤로갔다가 다시 돌아올때 제목이 저장안되는 버그 -> 수정하였습니다.
3. 작업대위의 컨텐츠 드래그&드랍 이동시 컨텐츠 패널과의 동기화 관련하여 발생하는 에러 -> 드래그시 컨텐츠패널이 닫히고 드랍시 포커스도 풀리도록 수정하였습니다.

2023-03-11 22:56 UTC, roadzmoon76 requested changes
1번이 원인이 될만한 곳이 왜 원인이 될만한 곳이였는지, 그래서 어떤 방식으로 방어로직을 추가한건지 설명 부탁드립니다.

2023-03-12 01:35 UTC, roadzmoon76 commented on src/pages/emails/EmailEditingStep03.jsx
>        setEmailContentsData(parsedEmailData);
parsedEmailData 가 없는데 set을 해주는게 에러 해결책은 아닌 것 같습니다.

2023-03-12 07:47 UTC, pinomad commented on src/pages/emails/EmailEditingStep03.jsx
>        setEmailContentsData(parsedEmailData);
해당로직은 의미가 없는거같아 다시 원복하였습니다

2023-03-12 15:00 UTC, roadzmoon76 approved these changes
step2 에서 3 넘어갈 때 나는 오류는 확실히 나는 조건을 모르니까 잡기 까다롭긴 하네요 ㅠㅠ

수고하셨습니다. 우선 다른 급한것들 부터 마무리 하고 나중에 다시 생각해봐요

2023-03-12 15:01 UTC, merged